name: CI
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  validate-node:
    name: 'Validate'
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    with:
      continue-on-prod-vulns: true
    secrets:
      SONARQUBE_KEY: ${{ secrets.SONARQUBE_KEY }}
  build-container:
    name: 'Build container image'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    needs: validate-node
    with:
      registry: ghcr.io/bryopsida
      image_name: object-store
      push_in_pr: true
